#!/bin/sh
set +x
export DOCKER_CLI_EXPERIMENTAL=enabled
docker run --rm --privileged tonistiigi/binfmt:latest --install all
docker buildx version
docker buildx create --use --name=asecurityteam-multiarch --driver docker-container
docker buildx ls
PLATFORM="linux/amd64,linux/arm64"
docker buildx build --push -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" --platform $PLATFORM .
