#!/bin/sh
set +x
sudo apt-get install -y qemu qemu-user-static qemu-user binfmt-support
update-binfmts --display
export DOCKER_CLI_EXPERIMENTAL=enabled
#docker run --rm --privileged tonistiigi/binfmt:latest --install all
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx version
docker buildx create --use --name=asecurityteam-multiarch --driver docker-container
docker buildx inspect --bootstrap 
docker buildx ls
PLATFORM="linux/amd64,linux/arm64"
docker buildx build --push -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" --platform $PLATFORM .
